// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using src;

#nullable disable

namespace src.Migrations
{
    [DbContext(typeof(BarContext))]
    [Migration("20220201213244_IngredientMigration2")]
    partial class IngredientMigration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("src.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("src.Models.Glass", b =>
                {
                    b.Property<int>("GlassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GlassId"));

                    b.HasKey("GlassId");

                    b.ToTable("Glasses");
                });

            modelBuilder.Entity("src.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IngredientId"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IngredientId");

                    b.HasIndex("BrandId");

                    b.ToTable("Ingredients");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Ingredient");
                });

            modelBuilder.Entity("src.Models.Fruit", b =>
                {
                    b.HasBaseType("src.Models.Ingredient");

                    b.HasDiscriminator().HasValue("Fruit");
                });

            modelBuilder.Entity("src.Models.Garnish", b =>
                {
                    b.HasBaseType("src.Models.Ingredient");

                    b.HasDiscriminator().HasValue("Garnish");
                });

            modelBuilder.Entity("src.Models.Liqueur", b =>
                {
                    b.HasBaseType("src.Models.Ingredient");

                    b.Property<double>("Percentage")
                        .HasColumnType("double precision");

                    b.HasDiscriminator().HasValue("Liqueur");
                });

            modelBuilder.Entity("src.Models.Liquor", b =>
                {
                    b.HasBaseType("src.Models.Ingredient");

                    b.Property<double>("Percentage")
                        .HasColumnType("double precision")
                        .HasColumnName("Liquor_Percentage");

                    b.HasDiscriminator().HasValue("Liquor");
                });

            modelBuilder.Entity("src.Models.Mixer", b =>
                {
                    b.HasBaseType("src.Models.Ingredient");

                    b.HasDiscriminator().HasValue("Mixer");
                });

            modelBuilder.Entity("src.Models.Ingredient", b =>
                {
                    b.HasOne("src.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });
#pragma warning restore 612, 618
        }
    }
}
